# Generated by Django 4.1 on 2022-08-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='DEFAULT VALUE', max_length=1000)),
                ('contenido', models.TextField(default='DEFAULT VALUE')),
                ('visible', models.BooleanField(default=False)),
                ('etiqueta', models.CharField(default='DEFAULT VALUE', max_length=1000)),
                ('imagen', models.CharField(default='DEFAULT VALUE', max_length=1000)),
                ('video', models.CharField(default='DEFAULT VALUE', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
    ]
